const mindarray = [
  {
    id: 1,
    image: "./img/mind1.jpg",
    name: "Briyani",
  },
  {
    id: 2,
    image: "./img/mind2.jpeg",
    name: "whiterice",
  },
  {
    id: 3,
    image: "./img/mind3.jpeg",
    name: "SwiteLattu",
  },
  {
    id: 4,
    image: "./img/mind4.jpeg",
    name: "BrownieShake",
  },
  {
    id: 5,
    image: "./img/mind5.jpeg",
    name: "Sandwich",
  },
  {
    id: 6,
    image: "./img/mind6.jpeg",
    name: "FruitsJuse",
  },
];

const chainsArray = [
  {
    id: 1,
    imag: "./img/food15.jpg",
    name: "McDonald",
    raiting: 4.1,
    cusine: "Burgers, Beverages",
    area: "OMR Navllur",
  },
  {
    id: 2,
    imag: "./img/food16.jpg",
    name: "Chikan Rice",
    raiting: 4.5,
    cusine: "Fast Foot, Beverages",
    area: "Anna Salai",
  },
  {
    id: 3,
    imag: "./img/food17.jpg",
    name: "TameBriyani",
    raiting: 4.4,
    cusine: "Briyani, Beverages",
    area: "Egmore",
  },
  {
    id: 4,
    imag: "./img/food18.jpg",
    name: "kalyanBriyani",
    raiting: 3.1,
    cusine: "kalyanBriyani, Beverages",
    area: "Annasalai",
  },
];

const restarantarray = [
  {
    id: 1,
    imag: "./img/food20.jpg",
    name: "Ice's",
    raiting: 4.1,
    cusine: "Arun Ice",
    area: "Chennai",
  },
  {
    id: 2,
    imag: "./img/food21.jpg",
    name: "Ban viggtaple",
    raiting: 4.4,
    cusine: "Burgers, Beverages",
    area: "Centrl Chennai",
  },
  {
    id: 3,
    imag: "./img/food22.jpg",
    name: "White Rice",
    raiting: 4.2,
    cusine: "Beverages",
    area: "Tambaram",
  },
  {
    id: 4,
    imag: "./img/food23.jpg",
    name: "Mattan Baya",
    raiting: 3.4,
    cusine: "Baya, Beverages",
    area: "North Chennai",
  },
];

const resArrayDt = [
  {
    id: 1,
    favShopname: "Veg Briyani & Baath Briyani Nan Veg",
    quality:
      "Deliciously soft and healthy Baath Briyani Nan Veg for an Briyani Dinner.",
    totelhotel: "100 restaurants to explore",
    images: "./img/food1.jpg",
    foodname:
      "Veg Briyani, Mutton Briyani, Chicken Briyani, Fish Briyani, Switte Burger, Jaklate Burger Bizza, SandVeg Burger ",
    raiting: 4.2,
    cusine: "Arun Briyani",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "Geetham",
        quality: "Deliciously soft and healthy Briyani for an Briyani Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/foodveg.jpeg",
        foodname: "veg-briyani",
        raiting: 4.5,
        cusine: "Arun Briyani",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "venketswara",
        quality: "Deliciously soft and healthy Briyani for an Briyani Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food9.jpg",
        foodname: "mutton briyani",
        raiting: 4.1,
        cusine: "Beverages Briyani",
        location: "Centrl Chennai",
      },
      {
        id: 3,
        favShopname: "arusuvai",
        quality: "Deliciously soft and healthy Briyani for an Briyani Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food16.jpg",
        foodname: "chicken briyani",
        raiting: 4.5,
        cusine: "Arun Briyani",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "indianshop",
        quality: "Deliciously soft and healthy Briyani for an Briyani Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/fish.jpeg",
        foodname: "fish frai",
        raiting: 4.3,
        cusine: " Baya, Beveragesi",
        location: "North Chennai",
      },
      {
        id: 5,
        favShopname: "jonusstal",
        quality: "Deliciously soft and Burger Bizza for an Burger Bizza sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food15.jpg",
        foodname: "burger shop",
        raiting: 4.1,
        cusine: "Arun Burger Bizza Bark",
        location: "North Chennai",
      },
      {
        id: 6,
        favShopname: "fastfood",
        quality: "Deliciously soft and Burger Bizza for an Burger Bizza sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food14.jpg",
        foodname: "Jaklate shop",
        raiting: 3.2,
        cusine: "Arun Burger Bizza Bark",
        location: "Tambaram",
      },
      {
        id: 7,
        favShopname: "mcSaverstal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food26.jpg",
        foodname: "SandVeg Burger",
        raiting: 4.3,
        cusine: "Arun Burger Bizza Bark",
        location: "OMR Navlur",
      },
    ],
  },
  {
    id: 2,
    favShopname: "Pure Veg White rice100",
    quality:
      "Deliciously soft and healthy Pure Veg White rice for an Rice Dinner.",
    totelhotel: "100 restaurants to explore",
    images: "./img/food2.jpg",
    foodname: " whiterice, NonVegwhiterice, IddlyWhiterice, ThosiWhiterice",
    raiting: 4.5,
    cusine: "whiterice",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "atheraMeals",
        quality: "Deliciously soft and healthy rice for an rice Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food2.jpg",
        foodname: "whiterice",
        raiting: 4.2,
        cusine: "Veg whiterice",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "sarvanpavan",
        quality:
          "Deliciously soft and healthy Non Veg whiterice for an Non Veg whiterice Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food11.jpg",
        foodname: "NonVegwhiterice",
        raiting: 4.1,
        cusine: "Veg whiterice",
        location: "North Chennai",
      },
      {
        id: 3,
        favShopname: "borderstall",
        quality:
          "Deliciously soft and healthy Iddly Whiterice for an Iddly Whiterice Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food12.jpg",
        foodname: "IddlyWhiterice",
        raiting: 3.2,
        cusine: "Iddly Whiterice",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "ricestall",
        quality:
          "Deliciously soft and healthy Non Thosi Whiterice for an Non Thosi Whiterice Dinner.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food25.jpg",
        foodname: "ThosiWhiterice",
        raiting: 4.4,
        cusine: "Thosi Whiterice",
        location: "OMR Navlur",
      },
    ],
  },
  {
    id: 3,
    favShopname: "SwiteCapi",
    quality: "Deliciously soft and healthy Cake swite for an swite  snaks.",
    totelhotel: "100 restaurants to explore",
    images: "./img/food3.jpg",
    foodname: "SwiteLattu, CakeSwite, iceCakeSwite, SwiteCapi",
    raiting: 4.5,
    cusine: "swite stall",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "starstall",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food3.jpg",
        foodname: "SwiteLattu",
        raiting: 4.2,
        cusine: "swite stall",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "goodnightstal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food20.jpg",
        foodname: "CakeSwite",
        raiting: 4.1,
        cusine: "swite stall",
        location: "North Chennai",
      },
      {
        id: 3,
        favShopname: "chennaisweet",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food27.jpg",
        foodname: "iceCakeSwite",
        raiting: 3.2,
        cusine: "swite stall",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "nanbastal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food28.jpg",
        foodname: "SwiteCapi",
        raiting: 4.3,
        cusine: "swite stall",
        location: "OMR Navlur",
      },
    ],
  },

  {
    id: 4,
    favShopname: "IceShakas",
    quality: "Deliciously soft and Ice Shakas for an Ice sanks.",
    totelhotel: "100 restaurants to explore",
    images: "./img/food4.jpg",
    foodname: "BrownieShake, BluelimeMojito, FruitFalooda, BlueberryLassi",
    raiting: 4.5,
    cusine: "Arun Ice Bark",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "nallaistal",
        quality: "Deliciously soft and Ice for an Ice sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food4.jpg",
        foodname: "BrownieShake",
        raiting: 4.2,
        cusine: "Arun Ice Bark",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "baisweetstal",
        quality: "Deliciously soft and Ice for an Ice sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food19.jpg",
        foodname: "BluelimeMojito",
        raiting: 4.1,
        cusine: "Arun Ice Bark",
        location: "North Chennai",
      },
      {
        id: 3,
        favShopname: "maduraistal",
        quality: "Deliciously soft and Ice for an Ice sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food24.jpg",
        foodname: "FruitFalooda",
        raiting: 3.2,
        cusine: "Arun Ice Bark",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "kinghstal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food27.jpg",
        foodname: "BlueberryLassi",
        raiting: 4.3,
        cusine: "Arun Ice Bark",
        location: "OMR Navlur",
      },
      {
        id: 5,
        favShopname: "railsweetstal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food2.jpg",
        foodname: "BlueberryLassi",
        raiting: 4.3,
        cusine: "Arun Ice Bark",
        location: "OMR Navlur",
      },
    ],
  },
  {
    id: 5,
    favShopname: "SandVeg Burger Bizza",
    quality: "Deliciously soft and Burger Bizza for an Burger Bizza sanks.",
    totelhotel: "100 restaurants to explore",
    images: "./img/food5.jpg",
    foodname: "Sandwich, SwitteBurger, JaklateBurger, SandVeg",
    raiting: 4.5,
    cusine: "Arun Burger Bizza",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "jainessatal",
        quality:
          "Deliciously soft and SandVeg Burger Burger Bizza for an Burger Bizza sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food5.jpg",
        foodname: "Sandwich",
        raiting: 4.2,
        cusine: "Arun Burger Bizza Bark",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "chikanricestal",
        quality: "Deliciously soft and Burger Bizza for an Burger Bizza sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food15.jpg",
        foodname: "SwitteBurger",
        raiting: 4.1,
        cusine: "Arun Burger Bizza Bark",
        location: "North Chennai",
      },
      {
        id: 3,
        favShopname: "lookstal",
        quality: "Deliciously soft and Burger Bizza for an Burger Bizza sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food14.jpg",
        foodname: "JaklateBurger",
        raiting: 3.2,
        cusine: "Arun Burger Bizza Bark",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "SandVegstal",
        quality: "Deliciously soft and healthy swite for an swite snaks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food26.jpg",
        foodname: "SandVeg",
        raiting: 4.3,
        cusine: "Arun Burger Bizza Bark",
        location: "OMR Navlur",
      },
    ],
  },
  {
    id: 6,
    favShopname: "Fruits Juse",
    quality: "Deliciously soft and Fruits Juse for an Fruits Jusea sanks.",
    totelhotel: "120 restaurants to explore",
    images: "./img/food6.jpg",
    foodname: "FruitsJuse, SwitteFruits, JaklateFruitsJuse, MilkFruitsJuse",
    raiting: 4.5,
    cusine: "Arun Fruits Juse",
    location: "Chennai",
    relatedProductLists: [
      {
        id: 1,
        favShopname: "icejusebark",
        quality: "Deliciously soft and Fruits Juse for an Fruits Jusea sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food4.jpg",
        foodname: "FruitsJuse",
        raiting: 4.2,
        cusine: "Arun Fruits Juse ",
        location: "Chennai",
      },
      {
        id: 2,
        favShopname: "furtesjues",
        quality: "Deliciously soft and Fruits Juse for an Fruits Jusea sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food6.jpg",
        foodname: "SwitteFruits",
        raiting: 4.1,
        cusine: "Arun Fruits Juse Bark",
        location: "North Chennai",
      },
      {
        id: 3,
        favShopname: "miklstal",
        quality: "Deliciously soft and Fruits Juse for an Fruits Jusea sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food7.jpg",
        foodname: "JaklateFruitsJuse",
        raiting: 3.2,
        cusine: "Arun Fruits Juse Bark",
        location: "Tambaram",
      },
      {
        id: 4,
        favShopname: "milkjak",
        quality: "Deliciously soft and Fruits Juse for an Fruits Jusea sanks.",
        totelhotel: "100 restaurants to explore",
        images: "./img/food19.jpg",
        foodname: "MilkFruitsJuse",
        raiting: 4.3,
        cusine: "ArunFruits Juse",
        location: "OMR Navlur",
      },
    ],
  },
];

{
  /* <script src="main.js"></script> */
}

// console.log(mindarray);
// console.log(chainsArray);
// console.log(restarantarray);
// console.log(resArrayDt);
